---

- name: Migrate Management vmk
    local_action:
    module: vmware_migrate_vmk
    hostname: {{ vcsa_host }}
    username: {{ vcsa_user }}
    password: {{ vcsa_pass }}
    esxi_hostname: esxi_hostname
    device: vmk1
    current_switch_name: vswitch0
    current_portgroup_name: "Management Network"
    migrate_switch_name: dvSwitch0
    migrate_portgroup_name: SManagement
