---

#- hosts: all
#  tasks:
#    - include: /trilian-dvs/Ansible/roles/vsphere/tasks/migrate_mgmt_to_dvs.yml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create mgmt dvswitch
      local_action:
        module: vmware_dvswitch
        hostname: "{{ hostvars[groups['vc_hosts'][0]]['ansible_ssh_host'] }}"
        username: "{{ vmware_vcsa_user }}"
        password: "{{ vmware_vcsa_pass }}"
        datacenter_name: "{{ vmware_datacenter_name }}"
        switch_name: dvSwitch-mgmt
        mtu: 1500
        uplink_quantity: 1
        discovery_proto: lldp
        discovery_operation: both
        state: present
        validate_certs: false

    - name: Create Management portgroup on dvSwitch
      local_action:
        module: vmware_dvs_portgroup
        hostname: "{{ hostvars[groups['vc_hosts'][0]]['ansible_ssh_host'] }}"
        username: "{{ vmware_vcsa_user }}"
        password: "{{ vmware_vcsa_pass }}"
        portgroup_name: 'Management Network'
        switch_name: dvSwitch-mgmt
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
        vlan_id: 0
        validate_certs: false

#    - name: Add Host to dVS
#      local_action:
#        module: vmware_dvs_host
#        hostname: "{{ hostvars[groups['vc_hosts'][0]]['ansible_ssh_host'] }}"
#        username: "{{ vmware_vcsa_user }}"
#        password: "{{ vmware_vcsa_pass }}"
#        esxi_hostname: "10.2.2.20"
#        switch_name: dvSwitch-mgmt
#        vmnics:
#            - vmnic0
#        state: present

    - name: Migrate Management vmk
      local_action:
        module: vmware_migrate_vmk
        hostname: "{{ hostvars[groups['vc_hosts'][0]]['ansible_ssh_host'] }}"
        username: "{{ vmware_vcsa_user }}"
        password: "{{ vmware_vcsa_pass }}"
        esxi_hostname: esxi_hostname
        device: vmk0
        current_switch_name: vSwitch0
        current_portgroup_name: "Management Network"
        migrate_switch_name: dvSwitch-mgmt
        migrate_portgroup_name: "Management Network"
